name: Leap
main: net.avicus.leap.Leap
version: 2.0
depend: [Avicus]
softdepend: [NoCheatPlus]
author: IvyCode
description: >
             LEAP! Double jump!
commands:
  trail:
    aliases: [trails]
    description: Modify your double jump trail
    usage: /trail (name)
    default: true