# Leap v2.0 Configuration File

# EFFECTS # http://jd.bukkit.org/rb/apidocs/org/bukkit/Effect.html #
# Effects that are fired upon using Leap
# Format: "effect name:the.permission.needed"
# Do not include a permission to allow the effect for all players.
effects:
- smoke:leap.smoke
- mobspawner flames:leap.flames
- ender signal:leap.ender
- potion break:leap.potion

# SOUNDS # http://jd.bukkit.org/rb/apidocs/org/bukkit/Sound.html #
# Sounds that are fired upon using Leap
# Format: "sound name"
sounds:
- bat takeoff
- enderdragon wings
- shoot arrow

# TRAILS # https://github.com/funkystudios/Leap #
# Remove trails from the list to disable them
trails:
- Cloud
- Critical
- Ember
- Ender
- Explosion
- Fire
- Heart
- Portal
- Rainbow
- Runes
- Slime
- Snow
- Void

# MOVEMENT #
velocity: 2.0
elevation: 1.5

