name: Leap
main: net.avicus.leap.Leap
version: 3.0
softdepend: [NoCheatPlus]
authors: [IvyCode, dentmaged]
description: >
             LEAP! Double jump!
commands:
  trail:
    aliases: [trails]
    description: Modify your double jump trail
    usage: /trail (name)
    default: true

permissions:
  leap.*:
   default: op